apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: CodeOpsEditor
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: vkunal/napptive_hackathon:VERSION
        ports:
          - port: 3000
            expose: true
      traits:
        - type: resource    
          properties:
            requests:
                cpu: 0.125
                memory: "300Mi"
            limits:
                cpu: 0.25
                memory: "500Mi" 
        - type: napptive-ingress      
          properties:
            name: nginx-ingress 
            port: 3000
            path: /  
            rewritePath: /